
package com.cams.webservices.skeleton.cpq.datatable;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-b02-
 * Generated source version: 2.1
 * 
 */
@WebFault(name = "fault", targetNamespace = "http://xmlns.oracle.com/cpqcloud/dataTables/TbCustomer_Master")
public class BusinessLogicException
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private Fault faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public BusinessLogicException(String message, Fault faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public BusinessLogicException(String message, Fault faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.cams.webservices.skeleton.cpq.datatable.Fault
     */
    public Fault getFaultInfo() {
        return faultInfo;
    }

}
