
package com.cams.webservices.skeleton.cpq.datatable;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-b02-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "DataTablesService", targetNamespace = "http://xmlns.oracle.com/cpqcloud/dataTables/TbCustomer_Master", wsdlLocation = "https://glesbymarks.bigmachines.com/v2_0/receiver/dataTables/36710317?WSDL")
public class DataTablesService
    extends Service
{

    private final static URL DATATABLESSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.cams.webservices.skeleton.cpq.datatable.DataTablesService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.cams.webservices.skeleton.cpq.datatable.DataTablesService.class.getResource(".");
            url = new URL(baseUrl, "https://glesbymarks.bigmachines.com/v2_0/receiver/dataTables/36710317?WSDL");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'https://glesbymarks.bigmachines.com/v2_0/receiver/dataTables/36710317?WSDL', retrying as a local file");
            logger.warning(e.getMessage());
        }
        DATATABLESSERVICE_WSDL_LOCATION = url;
    }

    public DataTablesService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DataTablesService() {
        super(DATATABLESSERVICE_WSDL_LOCATION, new QName("http://xmlns.oracle.com/cpqcloud/dataTables/TbCustomer_Master", "DataTablesService"));
    }

    /**
     * 
     * @return
     *     returns DataTablesServicePortType
     */
    @WebEndpoint(name = "DataTablesServicePort")
    public DataTablesServicePortType getDataTablesServicePort() {
        return super.getPort(new QName("http://xmlns.oracle.com/cpqcloud/dataTables/TbCustomer_Master", "DataTablesServicePort"), DataTablesServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DataTablesServicePortType
     */
    @WebEndpoint(name = "DataTablesServicePort")
    public DataTablesServicePortType getDataTablesServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://xmlns.oracle.com/cpqcloud/dataTables/TbCustomer_Master", "DataTablesServicePort"), DataTablesServicePortType.class, features);
    }

}
