
package com.cams.webservices.skeleton.cpq.datatable;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-b02-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "DataTablesServicePortType", targetNamespace = "http://xmlns.oracle.com/cpqcloud/dataTables/TbCustomer_Master")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface DataTablesServicePortType {


    /**
     * 
     * @param add
     * @return
     *     returns com.cams.webservices.skeleton.cpq.datatable.AddResponse
     * @throws BusinessLogicException
     */
    @WebMethod
    @WebResult(name = "addResponse", targetNamespace = "http://xmlns.oracle.com/cpqcloud/dataTables/TbCustomer_Master", partName = "addResponse")
    public AddResponse add(
        @WebParam(name = "add", targetNamespace = "http://xmlns.oracle.com/cpqcloud/dataTables/TbCustomer_Master", partName = "add")
        Add add)
        throws BusinessLogicException
    ;

    /**
     * 
     * @param get
     * @return
     *     returns com.cams.webservices.skeleton.cpq.datatable.GetResponse
     * @throws BusinessLogicException
     */
    @WebMethod
    @WebResult(name = "getResponse", targetNamespace = "http://xmlns.oracle.com/cpqcloud/dataTables/TbCustomer_Master", partName = "getResponse")
    public GetResponse get(
        @WebParam(name = "get", targetNamespace = "http://xmlns.oracle.com/cpqcloud/dataTables/TbCustomer_Master", partName = "get")
        Get get)
        throws BusinessLogicException
    ;

    /**
     * 
     * @param delete
     * @return
     *     returns com.cams.webservices.skeleton.cpq.datatable.DeleteResponse
     * @throws BusinessLogicException
     */
    @WebMethod
    @WebResult(name = "deleteResponse", targetNamespace = "http://xmlns.oracle.com/cpqcloud/dataTables/TbCustomer_Master", partName = "deleteResponse")
    public DeleteResponse delete(
        @WebParam(name = "delete", targetNamespace = "http://xmlns.oracle.com/cpqcloud/dataTables/TbCustomer_Master", partName = "delete")
        Delete delete)
        throws BusinessLogicException
    ;

    /**
     * 
     * @param update
     * @return
     *     returns com.cams.webservices.skeleton.cpq.datatable.UpdateResponse
     * @throws BusinessLogicException
     */
    @WebMethod
    @WebResult(name = "updateResponse", targetNamespace = "http://xmlns.oracle.com/cpqcloud/dataTables/TbCustomer_Master", partName = "updateResponse")
    public UpdateResponse update(
        @WebParam(name = "update", targetNamespace = "http://xmlns.oracle.com/cpqcloud/dataTables/TbCustomer_Master", partName = "update")
        Update update)
        throws BusinessLogicException
    ;

    /**
     * 
     * @param deploy
     * @return
     *     returns com.cams.webservices.skeleton.cpq.datatable.DeployResponse
     * @throws BusinessLogicException
     */
    @WebMethod
    @WebResult(name = "deployResponse", targetNamespace = "http://xmlns.oracle.com/cpqcloud/dataTables/TbCustomer_Master", partName = "deployResponse")
    public DeployResponse deploy(
        @WebParam(name = "deploy", targetNamespace = "http://xmlns.oracle.com/cpqcloud/dataTables/TbCustomer_Master", partName = "deploy")
        Deploy deploy)
        throws BusinessLogicException
    ;

}
