
package com.cams.webservices.skeleton.gps;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-b02-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "WSTrack2", targetNamespace = "http://www.tempuri.org/", wsdlLocation = "http://v8.skyeyegpstracking.com/WS/WSTrack2.asmx?WSDL")
public class WSTrack2
    extends Service
{

    private final static URL WSTRACK2_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.cams.webservices.skeleton.gps.WSTrack2 .class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.cams.webservices.skeleton.gps.WSTrack2 .class.getResource(".");
            url = new URL(baseUrl, "http://v8.skyeyegpstracking.com/WS/WSTrack2.asmx?WSDL");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://v8.skyeyegpstracking.com/WS/WSTrack2.asmx?WSDL', retrying as a local file");
            logger.warning(e.getMessage());
        }
        WSTRACK2_WSDL_LOCATION = url;
    }

    public WSTrack2(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WSTrack2() {
        super(WSTRACK2_WSDL_LOCATION, new QName("http://www.tempuri.org/", "WSTrack2"));
    }

    /**
     * 
     * @return
     *     returns WSTrack2Soap
     */
    @WebEndpoint(name = "WSTrack2Soap")
    public WSTrack2Soap getWSTrack2Soap() {
        return super.getPort(new QName("http://www.tempuri.org/", "WSTrack2Soap"), WSTrack2Soap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WSTrack2Soap
     */
    @WebEndpoint(name = "WSTrack2Soap")
    public WSTrack2Soap getWSTrack2Soap(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.tempuri.org/", "WSTrack2Soap"), WSTrack2Soap.class, features);
    }

}
