
package com.cams.webservices.skeleton.chromedata;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-b02-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "AutomotiveConfigCompareService4g", targetNamespace = "urn:configcompare4g.kp.chrome.com", wsdlLocation = "http://services.chromedata.com/AutomotiveConfigCompareService/AutomotiveConfigCompareService4g?WSDL")
public class AutomotiveConfigCompareService4G
    extends Service
{

    private final static URL AUTOMOTIVECONFIGCOMPARESERVICE4G_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.cams.webservices.skeleton.chromedata.AutomotiveConfigCompareService4G.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.cams.webservices.skeleton.chromedata.AutomotiveConfigCompareService4G.class.getResource(".");
            url = new URL(baseUrl, "http://services.chromedata.com/AutomotiveConfigCompareService/AutomotiveConfigCompareService4g?WSDL");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://services.chromedata.com/AutomotiveConfigCompareService/AutomotiveConfigCompareService4g?WSDL', retrying as a local file");
            logger.warning(e.getMessage());
        }
        AUTOMOTIVECONFIGCOMPARESERVICE4G_WSDL_LOCATION = url;
    }

    public AutomotiveConfigCompareService4G(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AutomotiveConfigCompareService4G() {
        super(AUTOMOTIVECONFIGCOMPARESERVICE4G_WSDL_LOCATION, new QName("urn:configcompare4g.kp.chrome.com", "AutomotiveConfigCompareService4g"));
    }

    /**
     * 
     * @return
     *     returns AutomotiveConfigCompareService4GPortType
     */
    @WebEndpoint(name = "AutomotiveConfigCompareService4gPort")
    public AutomotiveConfigCompareService4GPortType getAutomotiveConfigCompareService4GPort() {
        return super.getPort(new QName("urn:configcompare4g.kp.chrome.com", "AutomotiveConfigCompareService4gPort"), AutomotiveConfigCompareService4GPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AutomotiveConfigCompareService4GPortType
     */
    @WebEndpoint(name = "AutomotiveConfigCompareService4gPort")
    public AutomotiveConfigCompareService4GPortType getAutomotiveConfigCompareService4GPort(WebServiceFeature... features) {
        return super.getPort(new QName("urn:configcompare4g.kp.chrome.com", "AutomotiveConfigCompareService4gPort"), AutomotiveConfigCompareService4GPortType.class, features);
    }

}
